apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global: 
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.163.com:25'
      smtp_from: 'baojingtongzhi@163.com'
      smtp_auth_username: 'baojingtongzhi@163.com'
      smtp_auth_password: 'RYCHUQSZQIMMCSJA'

    templates:
    - '/etc/alertmanager/msg-tmpl/*.tmpl'

    route:
      receiver: 'default-receiver'
      group_by: [cluster, alertname]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 30m
      
    receivers:
    - name: 'default-receiver'
      email_configs:
      - to: 'user1@aliangedu.cn'
        send_resolved: true
        html: '{{ template "emailMessage" . }}'
