apiVersion: apps/v1
kind: Deployment   
metadata:          
  name: flask-app
spec:              
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:         
    metadata:      
      labels:
        app: flask
      annotations:
        prometheus.io/scrape: "true"  # 声明监控Pod
        prometheus.io/port: "8001"
    spec:
      containers:
      - image: lizhenliang/flask-app-metrics:latest
        name: web
---
apiVersion: v1        
kind: Service         
metadata:             
  name: flask-app   
  annotations: 
    prometheus.io/probe: "http"  # 声明监控Service
spec:                 
  ports:              
  - name: http
    port: 80            
    targetPort: 80 
  selector:           
    app: flask
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app
  annotations: 
    prometheus.io/probe: "http"  # 声明监控Ingress
spec:
  ingressClassName: nginx
  rules:
  - host: blog.aliangedu.cn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask
            port:
              number: 80
